local M = {}

---@param colors BackpackColors
---@param config? BackpackConfig
function M.setup(colors, config)
    config = config or require("backpack").config

    local theme = colors.theme

    return {
        -- Neovcs
        -- NeovcsBranch = {},
        -- NeovcsRemote = {},
        -- NeovcsDiffDelete = { fg = theme.vcs.removed, bg = theme.diff.delete },
        -- NeovcsDiffAdd = { fg = theme.vcs.added, bg = theme.diff.add },
        -- NeovcsHunkHeader = { fg = theme.syn.identifier },
        -- NeovcsDiffContextHighlight = { bg = theme.diff.change },

        -- vcsSigns
        -- vcsSignsAdd = { link = "diffAdded" },
        -- vcsSignsChange = { link = "diffChanged" },
        -- vcsSignsDelete = { link = "diffDeleted" },
        -- vcsSignsDeleteLn = { bg = theme.diff.delete },

        -- Gitsigns
        GitSignsAdd = { fg = theme.vcs.added, bg = theme.ui.bg_gutter },
        GitSignsChange = { fg = theme.vcs.changed, bg = theme.ui.bg_gutter },
        GitSignsDelete = { fg = theme.vcs.removed, bg = theme.ui.bg_gutter },
        -- Neogit
        NeogitDiffContextHighlight = { bg = theme.diff.change }, --[[  guibg=#333333 guifg=#b2b2b2 ]]
        NeogitHunkHeader = { fg = theme.syn.fun }, --[[  guifg=#cccccc guibg=#404040 ]]
        NeogitHunkHeaderHighlight = { fg = theme.syn.constant, bg = theme.diff.change }, --[[ guifg=#cccccc guibg=#4d4d4d ]]
        NeogitDiffAddHighlight = { bg = theme.diff.add },
        NeogitDiffDeleteHighlight = { bg = theme.diff.delete },
        -- TreeSitter Extensions
        TreesitterContext = { link = "Folded" },
        TreesitterContextLineNumber = { fg = theme.ui.special, bg = theme.ui.bg_gutter },
        -- Telescope
        TelescopeBorder = { fg = theme.ui.float.fg_border, bg = theme.ui.bg },
        TelescopeTitle = { fg = theme.ui.special },
        TelescopeSelection = { link = "CursorLine" },
        TelescopeSelectionCaret = { link = "CursorLineNr" },
        TelescopeResultsClass = { link = "Structure" },
        TelescopeResultsStruct = { link = "Structure" },
        TelescopeResultsField = { link = "@field" },
        TelescopeResultsMethod = { link = "Function" },
        TelescopeResultsVariable = { link = "@variable" },
        -- NvimTree
        NvimTreeNormal = { link = "Normal" },
        NvimTreeNormalNC = { link = "NvimTreeNormal" },
        NvimTreeRootFolder = { fg = theme.syn.identifier, bold = true },
        NvimTreeGitDirty = { fg = theme.vcs.changed },
        NvimTreeGitNew = { fg = theme.vcs.added },
        NvimTreeGitDeleted = { fg = theme.vcs.removed },
        NvimTreeGitStaged = { fg = theme.vcs.added },
        NvimTreeSpecialFile = { fg = theme.syn.special1 },
        -- NvimTreeIndentMarker           = {},
        NvimTreeImageFile = { fg = theme.syn.special2 },
        NvimTreeSymlink = { link = "Type" },
        NvimTreeFolderName = { link = "Directory" },
        NvimTreeExecFile = { fg = theme.syn.string, bold = true },
        NvimTreeOpenedFile = { fg = theme.syn.special1, italic = true },
        NvimTreeWinSeparator = { link = "WinSeparator" },
        NvimTreeWindowPicker = { bg = theme.ui.bg_m1, fg = theme.syn.special1, bold = true },
        -- NeoTree
        NeoTreeTabInactive = { link = "TabLine" },
        NeoTreeTabActive = { link = "TabLineSel" },
        NeoTreeTabSeparatorInactive = { link = "NeoTreeTabInactive" },
        NeoTreeTabSeparatorActive = { link = "NeoTreeTabActive" },
        NeoTreeRootName = { fg = theme.syn.identifier, bold = true },
        NeoTreeModified = { link = "String" },
        NeoTreeGitUnstaged = { link = "NeoTreeGitModified", default = true },
        NeoTreeIndentMarker = { link = "NonText" },
        -- WindowPicker
        -- NvimWindowSwitch = { bg = theme.ui.bg_m3, fg = theme.diag.warning },
        -- NvimWindowSwitchNC = { link = "NvimWindowSwitch" },
        -- Dashboard
        DashboardShortCut = { fg = theme.syn.special1 },
        DashboardHeader = { fg = theme.vcs.removed },
        DashboardCenter = { fg = theme.syn.identifier },
        DashboardFooter = { fg = theme.syn.comment },
        DashboardDesc = { fg = theme.syn.identifier },
        DashboardKey = { fg = theme.syn.special1 },
        DashboardIcon = { fg = theme.ui.special },
        -- Notify
        NotifyBackground = { bg = theme.ui.bg },
        NotifyERRORBorder = { link = "DiagnosticError" },
        NotifyWARNBorder = { link = "DiagnosticWarn" },
        NotifyINFOBorder = { link = "DiagnosticInfo" },
        NotifyHINTBorder = { link = "DiagnosticHint" },
        NotifyDEBUGBorder = { link = "Debug" },
        NotifyTRACEBorder = { link = "Comment" },
        NotifyERRORIcon = { link = "DiagnosticError" },
        NotifyWARNIcon = { link = "DiagnosticWarn" },
        NotifyINFOIcon = { link = "DiagnosticInfo" },
        NotifyHINTIcon = { link = "DiagnosticHint" },
        NotifyDEBUGIcon = { link = "Debug" },
        NotifyTRACEIcon = { link = "Comment" },
        NotifyERRORTitle = { link = "DiagnosticError" },
        NotifyWARNTitle = { link = "DiagnosticWarn" },
        NotifyINFOTitle = { link = "DiagnosticInfo" },
        NotifyHINTTitle = { link = "DiagnosticHint" },
        NotifyDEBUGTitle = { link = "Debug" },
        NotifyTRACETitle = { link = "Comment" },
        -- Dap-UI
        -- DapUIVariable = { link = "Normal" },
        DapUIScope = { link = "Special" }, -- guifg=#00F1F5"
        DapUIType = { link = "Type" }, -- guifg=#D484FF"
        -- DapUIValue = { link = "Normal" },
        DapUIModifiedValue = { fg = theme.syn.special1, bold = true }, -- guifg=#00F1F5 gui=bold"
        DapUIDecoration = { fg = theme.ui.float.fg_border }, -- guifg=#00F1F5"
        DapUIThread = { fg = theme.syn.identifier }, --guifg=#A9FF68"
        DapUIStoppedThread = { fg = theme.syn.special1 }, --guifg=#00f1f5"
        -- DapUIFrameName = { link = "Normal"},
        DapUISource = { fg = theme.syn.special2 }, -- guifg=#D484FF"
        DapUILineNumber = { fg = theme.syn.special1 }, -- guifg=#00f1f5"
        DapUIFloatBorder = { fg = theme.ui.float.fg_border }, -- guifg=#00F1F5"
        DapUIWatchesEmpty = { fg = theme.diag.error }, -- guifg=#F70067"
        DapUIWatchesValue = { fg = theme.syn.identifier }, -- guifg=#A9FF68"
        DapUIWatchesError = { fg = theme.diag.error }, --guifg=#F70067"
        DapUIBreakpointsPath = { link = "Directory" }, --guifg=#00F1F5"
        DapUIBreakpointsInfo = { fg = theme.diag.info }, --guifg=#A9FF68"
        DapUIBreakpointsCurrentLine = { fg = theme.syn.identifier, bold = true }, --guifg=#A9FF68 gui=bold"
        -- DapUIBreakpointsLine = {}, -- DapUILineNumber"
        DapUIBreakpointsDisabledLine = { link = "Comment" }, --guifg=#424242"
        -- DapUICurrentFrameName = {}, -- DapUIBreakpointsCurrentLine"
        DapUIStepOver = { fg = theme.syn.special1 }, --guifg=#00f1f5"
        DapUIStepInto = { fg = theme.syn.special1 }, --guifg=#00f1f5"
        DapUIStepBack = { fg = theme.syn.special1 }, --guifg=#00f1f5"
        DapUIStepOut = { fg = theme.syn.special1 }, --guifg=#00f1f5"
        DapUIStop = { fg = theme.diag.error }, --guifg=#F70067"
        DapUIPlayPause = { fg = theme.syn.string }, --guifg=#A9FF68"
        DapUIRestart = { fg = theme.syn.string }, --guifg=#A9FF68"
        DapUIUnavailable = { fg = theme.syn.comment }, --guifg=#424242"
        -- Floaterm
        FloatermBorder = { fg = theme.ui.float.fg_border, bg = theme.ui.bg },
        -- NeoVim                         = {},
        healthError = { fg = theme.diag.error },
        healthSuccess = { fg = theme.diag.ok },
        healthWarning = { fg = theme.diag.warning },
        -- Cmp
        CmpDocumentation = { link = "NormalFloat" },
        CmpDocumentationBorder = { link = "FloatBorder" },
        CmpCompletion = { link = "Pmenu" },
        CmpCompletionSel = { link = "PmenuSel" },
        CmpCompletionBorder = { fg = theme.ui.bg_search, bg = theme.ui.pmenu.bg },
        CmpCompletionThumb = { link = "PmenuThumb" },
        CmpCompletionSbar = { link = "PmenuSbar" },
        CmpItemAbbr = { fg = theme.ui.pmenu.fg },
        CmpItemAbbrDeprecated = { fg = theme.syn.comment, strikethrough = true },
        CmpItemAbbrMatch = { fg = theme.syn.fun },
        CmpItemAbbrMatchFuzzy = { link = "CmpItemAbbrMatch" },
        CmpItemKindDefault = { fg = theme.ui.fg_dim },
        CmpItemMenu = { fg = theme.ui.fg_dim },
        CmpGhostText = { fg = theme.syn.comment },

        CmpItemKindText = { fg = theme.ui.fg },
        CmpItemKindMethod = { link = "@function.method" },
        CmpItemKindFunction = { link = "Function" },
        CmpItemKindConstructor = { link = "@constructor" },
        CmpItemKindField = { link = "@variable.member" },
        CmpItemKindVariable = { fg = theme.ui.fg_dim },
        CmpItemKindClass = { link = "Type" },
        CmpItemKindInterface = { link = "Type" },
        CmpItemKindModule = { link = "@module" },
        CmpItemKindProperty = { link = "@property" },
        CmpItemKindUnit = { link = "Number" },
        CmpItemKindValue = { link = "String" },
        CmpItemKindEnum = { link = "Type" },
        CmpItemKindKeyword = { link = "Keyword" },
        CmpItemKindSnippet = { link = "Special" },
        CmpItemKindColor = { link = "Special" },
        CmpItemKindFile = { link = "Directory" },
        CmpItemKindReference = { link = "Special" },
        CmpItemKindFolder = { link = "Directory" },
        CmpItemKindEnumMember = { link = "Constant" },
        CmpItemKindConstant = { link = "Constant" },
        CmpItemKindStruct = { link = "Type" },
        CmpItemKindEvent = { link = "Type" },
        CmpItemKindOperator = { link = "Operator" },
        CmpItemKindTypeParameter = { link = "Type" },
        CmpItemKindCopilot = { link = "String" },

        -- blink.cmp
        BlinkCmpMenu = { link = "Pmenu" },
        BlinkCmpMenuSelection = { link = "PmenuSel" },
        BlinkCmpMenuBorder = { fg = theme.ui.bg_search, bg = theme.ui.pmenu.bg },
        BlinkCmpScrollBarThumb = { link = "PmenuThumb" },
        BlinkCmpScrollBarGutter = { link = "PmenuSbar" },
        BlinkCmpLabel = { fg = theme.ui.pmenu.fg },
        BlinkCmpLabelMatch = { fg = theme.syn.fun },
        BlinkCmpLabelDetails = { fg = theme.syn.comment },
        BlinkCmpLabelDeprecated = { fg = theme.syn.comment, strikethrough = true },
        BlinkCmpGhostText = { fg = theme.syn.comment },
        BlinkCmpDoc = { link = "NormalFloat" },
        BlinkCmpDocBorder = { link = "FloatBorder" },
        BlinkCmpDocCursorLine = { link = "Visual"},
        BlinkCmpSignatureHelp = { link = "NormalFloat" },
        BlinkCmpSignatureHelpBorder = { link = "FloatBorder" },
        BlinkCmpSignatureHelpActiveParameter = { link = "LspSignatureActiveParameter"},

        BlinkCmpKind = { fg = theme.ui.fg_dim },
        BlinkCmpKindText = { fg = theme.ui.fg },
        BlinkCmpKindMethod = { link = "@function.method" },
        BlinkCmpKindFunction = { link = "Function" },
        BlinkCmpKindConstructor = { link = "@constructor" },
        BlinkCmpKindField = { link = "@variable.member" },
        BlinkCmpKindVariable = { fg = theme.ui.fg_dim },
        BlinkCmpKindClass = { link = "Type" },
        BlinkCmpKindInterface = { link = "Type" },
        BlinkCmpKindModule = { link = "@module" },
        BlinkCmpKindProperty = { link = "@property" },
        BlinkCmpKindUnit = { link = "Number" },
        BlinkCmpKindValue = { link = "String" },
        BlinkCmpKindEnum = { link = "Type" },
        BlinkCmpKindKeyword = { link = "Keyword" },
        BlinkCmpKindSnippet = { link = "Special" },
        BlinkCmpKindColor = { link = "Special" },
        BlinkCmpKindFile = { link = "Directory" },
        BlinkCmpKindReference = { link = "Special" },
        BlinkCmpKindFolder = { link = "Directory" },
        BlinkCmpKindEnumMember = { link = "Constant" },
        BlinkCmpKindConstant = { link = "Constant" },
        BlinkCmpKindStruct = { link = "Type" },
        BlinkCmpKindEvent = { link = "Type" },
        BlinkCmpKindOperator = { link = "Operator" },
        BlinkCmpKindTypeParameter = { link = "Type" },
        BlinkCmpKindCopilot = { link = "String" },

        -- IndentBlankline
        IndentBlanklineChar = { fg = theme.ui.whitespace },
        IndentBlanklineSpaceChar = { fg = theme.ui.whitespace },
        IndentBlanklineSpaceCharBlankline = { fg = theme.ui.whitespace },
        IndentBlanklineContextChar = { fg = theme.ui.special },
        IndentBlanklineContextStart = { sp = theme.ui.special, underline = true },
        IblIndent = { fg = theme.ui.whitespace },
        IblWhitespace = { fg = theme.ui.whitespace },
        IblScope = { fg = theme.ui.special },
        -- Lazy
        LazyProgressTodo = { fg = theme.ui.nontext },

        -- Trouble
        TroubleIndent = { fg = theme.ui.whitespace },
        TroublePos = { fg = theme.ui.special },

        -- Nvim-Navic
        NavicIconsFile = { link = "Directory" },
        NavicIconsModule = { link = "@module" },
        NavicIconsNamespace = { link = "@module" },
        NavicIconsPackage = { link = "@module" },
        NavicIconsClass = { link = "Type" },
        NavicIconsMethod = { link = "@function.method" },
        NavicIconsProperty = { link = "@property" },
        NavicIconsField = { link = "@variable.member" },
        NavicIconsConstructor = { link = "@constructor" },
        NavicIconsEnum = { link = "Type" },
        NavicIconsInterface = { link = "Type" },
        NavicIconsFunction = { link = "Function" },
        NavicIconsVariable = { link = "@variable" },
        NavicIconsConstant = { link = "Constant" },
        NavicIconsString = { link = "String" },
        NavicIconsNumber = { link = "Number" },
        NavicIconsBoolean = { link = "Boolean" },
        NavicIconsArray = { link = "Type" },
        NavicIconsObject = { link = "Type" },
        NavicIconsKey = { link = "Identifier" },
        NavicIconsNull = { link = "Type" },
        NavicIconsEnumMember = { link = "Constant" },
        NavicIconsStruct = { link = "Structure" },
        NavicIconsEvent = { link = "Structure" },
        NavicIconsOperator = { link = "Operator" },
        NavicIconsTypeParameter = { link = "Type" },
        NavicText = { fg = theme.ui.fg },
        NavicSeparator = { fg = theme.ui.fg },

        -- Aerial icons
        AerialFileIcon = { link = "Directory" },
        AerialModuleIcon = { link = "@module" },
        AerialNamespaceIcon = { link = "@module" },
        AerialPackageIcon = { link = "@module" },
        AerialClassIcon = { link = "Type" },
        AerialMethodIcon = { link = "@function.method" },
        AerialPropertyIcon = { link = "@property" },
        AerialFieldIcon = { link = "@variable.member" },
        AerialConstructorIcon = { link = "@constructor" },
        AerialEnumIcon = { link = "Type" },
        AerialInterfaceIcon = { link = "Type" },
        AerialFunctionIcon = { link = "Function" },
        AerialVariableIcon = { link = "@variable" },
        AerialConstantIcon = { link = "Constant" },
        AerialStringIcon = { link = "String" },
        AerialNumberIcon = { link = "Number" },
        AerialBooleanIcon = { link = "Boolean" },
        AerialArrayIcon = { link = "Type" },
        AerialObjectIcon = { link = "Type" },
        AerialKeyIcon = { link = "Identifier" },
        AerialNullIcon = { link = "Type" },
        AerialEnumMemberIcon = { link = "Constant" },
        AerialStructIcon = { link = "Structure" },
        AerialEventIcon = { link = "Structure" },
        AerialOperatorIcon = { link = "Operator" },
        AerialTypeParameterIcon = { link = "Type" },

        -- Mini
        MiniAnimateCursor = { reverse = true, nocombine = true },
        MiniAnimateNormalFloat = { link = "NormalFloat" },

        MiniClueBorder = { link = "FloatBorder" },
        MiniClueDescGroup = { link = "DiagnosticFloatingWarn" },
        MiniClueDescSingle = { link = "NormalFloat" },
        MiniClueNextKey = { link = "DiagnosticFloatingHint" },
        MiniClueNextKeyWithPostkeys = { link = "DiagnosticFloatingError" },
        MiniClueSeparator = { link = "DiagnosticFloatingInfo" },
        MiniClueTitle = { link = "FloatTitle" },

        MiniCompletionActiveParameter = { underline = true },

        MiniCursorword = { underline = true },
        MiniCursorwordCurrent = { underline = true },

        MiniDepsChangeAdded = { link = "diffAdded" },
        MiniDepsChangeRemoved = { link = "diffRemoved" },
        MiniDepsHint = { fg = theme.diag.hint },
        MiniDepsInfo = { fg = theme.diag.info },
        MiniDepsMsgBreaking = { fg = theme.diag.warning },
        MiniDepsPlaceholder = { link = "Comment" },
        MiniDepsTitle = { link = "Title" },
        MiniDepsTitleError = { link = "DiffDelete" },
        MiniDepsTitleSame = { link = "DiffText" },
        MiniDepsTitleUpdate = { link = "DiffAdd" },

        MiniDiffSignAdd = { fg = theme.vcs.added, bg = theme.ui.bg_gutter },
        MiniDiffSignChange = { fg = theme.vcs.changed, bg = theme.ui.bg_gutter },
        MiniDiffSignDelete = { fg = theme.vcs.removed, bg = theme.ui.bg_gutter },
        MiniDiffOverAdd = { link = "DiffAdd" },
        MiniDiffOverChange = { link = "DiffText" },
        MiniDiffOverContext = { link = "DiffChange" },
        MiniDiffOverDelete = { link = "DiffDelete" },

        MiniFilesBorder = { link = "FloatBorder" },
        MiniFilesBorderModified = { link = "DiagnosticFloatingWarn" },
        MiniFilesCursorLine = { link = "CursorLine" },
        MiniFilesDirectory = { link = "Directory" },
        MiniFilesFile = { fg = theme.ui.fg },
        MiniFilesNormal = { link = "NormalFloat" },
        MiniFilesTitle = { fg = theme.ui.special, bg = theme.ui.float.bg_border, bold = true },
        MiniFilesTitleFocused = { fg = theme.ui.fg, bg = theme.ui.float.bg_border, bold = true },

        MiniHipatternsFixme = { fg = theme.ui.bg, bg = theme.diag.error, bold = true },
        MiniHipatternsHack = { fg = theme.ui.bg, bg = theme.diag.warning, bold = true },
        MiniHipatternsNote = { fg = theme.ui.bg, bg = theme.diag.info, bold = true },
        MiniHipatternsTodo = { fg = theme.ui.bg, bg = theme.diag.hint, bold = true },

        MiniIconsAzure = { fg = theme.syn.special1 },
        MiniIconsBlue = { fg = theme.syn.fun },
        MiniIconsCyan = { fg = theme.syn.type },
        MiniIconsGreen = { fg = theme.syn.string },
        MiniIconsGrey = { fg = theme.ui.fg },
        MiniIconsOrange = { fg = theme.syn.constant },
        MiniIconsPurple = { fg = theme.syn.keyword },
        MiniIconsRed = { fg = theme.syn.special3 },
        MiniIconsYellow = { fg = theme.syn.identifier },

        MiniIndentscopeSymbol = { fg = theme.syn.special1 },
        MiniIndentscopePrefix = { nocombine = true }, -- Make it invisible

        MiniJump = { link = "SpellRare" },

        MiniJump2dDim = { link = "Comment" },
        MiniJump2dSpot = { fg = theme.syn.constant, bold = true, nocombine = true },
        MiniJump2dSpotAhead = { fg = theme.diag.hint, bg = theme.ui.bg_dim, nocombine = true },
        MiniJump2dSpotUnique = { fg = theme.syn.special1, bold = true, nocombine = true },

        MiniMapNormal = { link = "NormalFloat" },
        MiniMapSymbolCount = { link = "Special" },
        MiniMapSymbolLine = { link = "Title" },
        MiniMapSymbolView = { link = "Delimiter" },

        MiniNotifyBorder = { link = "FloatBorder" },
        MiniNotifyNormal = { link = "NormalFloat" },
        MiniNotifyTitle = { link = "FloatTitle" },

        MiniOperatorsExchangeFrom = { link = "IncSearch" },

        MiniPickBorder = { link = "FloatBorder" },
        MiniPickBorderBusy = { link = "DiagnosticFloatingWarn" },
        MiniPickBorderText = { link = "FloatTitle" },
        MiniPickIconDirectory = { link = "Directory" },
        MiniPickIconFile = { link = "MiniPickNormal" },
        MiniPickHeader = { link = "DiagnosticFloatingHint" },
        MiniPickMatchCurrent = { link = "CursorLine" },
        MiniPickMatchMarked = { link = "Visual" },
        MiniPickMatchRanges = { link = "DiagnosticFloatingHint" },
        MiniPickNormal = { link = "NormalFloat" },
        MiniPickPreviewLine = { link = "CursorLine" },
        MiniPickPreviewRegion = { link = "IncSearch" },
        MiniPickPrompt = { fg = theme.syn.fun, bg = theme.ui.float.bg_border },

        MiniStarterCurrent = { nocombine = true },
        MiniStarterFooter = { fg = theme.syn.deprecated },
        MiniStarterHeader = { link = "Title" },
        MiniStarterInactive = { link = "Comment" },
        MiniStarterItem = { link = "Normal" },
        MiniStarterItemBullet = { link = "Delimiter" },
        MiniStarterItemPrefix = { fg = theme.diag.warning },
        MiniStarterSection = {  fg = theme.diag.ok },
        MiniStarterQuery = { fg = theme.diag.info },

        MiniStatuslineDevinfo = { fg = theme.ui.fg_dim, bg = theme.ui.bg_p1 },
        MiniStatuslineFileinfo = { fg = theme.ui.fg_dim, bg = theme.ui.bg_p1 },
        MiniStatuslineFilename = { fg = theme.ui.fg_dim, bg = theme.ui.bg_dim },
        MiniStatuslineInactive = { link = "StatusLineNC" },
        MiniStatuslineModeCommand = { fg = theme.ui.bg, bg = theme.syn.operator, bold = true },
        MiniStatuslineModeInsert = { fg = theme.ui.bg, bg = theme.diag.ok, bold = true },
        MiniStatuslineModeNormal = { fg = theme.ui.bg_m3, bg = theme.syn.fun, bold = true },
        MiniStatuslineModeOther = { fg = theme.ui.bg, bg = theme.syn.type, bold = true },
        MiniStatuslineModeReplace = { fg = theme.ui.bg, bg = theme.syn.constant, bold = true },
        MiniStatuslineModeVisual = { fg = theme.ui.bg, bg = theme.syn.keyword, bold = true },

        MiniSurround = { link = "IncSearch" },

        MiniTablineCurrent = { fg = theme.ui.fg_dim, bg = theme.ui.bg_p1, bold = true },
        MiniTablineFill = { link = "TabLineFill" },
        MiniTablineHidden = { fg = theme.ui.special, bg = theme.ui.bg_m3 },
        MiniTablineModifiedCurrent = { fg = theme.ui.bg_p1, bg = theme.ui.fg_dim, bold = true },
        MiniTablineModifiedHidden = { fg = theme.ui.bg_m3, bg = theme.ui.special },
        MiniTablineModifiedVisible = { fg = theme.ui.bg_m3, bg = theme.ui.special, bold = true },
        MiniTablineTabpagesection = { fg = theme.ui.fg, bg = theme.ui.bg_search, bold = true },
        MiniTablineVisible = { fg = theme.ui.special, bg = theme.ui.bg_m3, bold = true },

        MiniTestEmphasis = { bold = true },
        MiniTestFail = { fg = theme.diag.error, bold = true },
        MiniTestPass = { fg = theme.diag.ok, bold = true },

        MiniTrailspace = { bg = theme.vcs.removed },


        NeotestAdapterName = { fg = theme.syn.special3, },
        NeotestDir = { fg = theme.syn.fun, },
        NeotestExpandMarker = { fg = theme.syn.punct, bold = true, },
        NeotestFailed = { fg = theme.diag.error },
        NeotestFile = { fg = theme.syn.fun, },
        NeotestFocused = { bold = true, underline = true, },
        NeotestIndent = { fg = theme.ui.special, bold = true, },
        NeotestMarked = { fg = theme.diag.warning, italic = true, },
        NeotestNamespace = { fg = theme.syn.fun, },
        NeotestPassed = { fg = theme.diag.ok },
        NeotestRunning = { fg = theme.vcs.changed, },
        NeotestWinSelect = { fg = theme.diag.hint },
        NeotestSkipped = { fg = theme.syn.special1 },
        NeotestTarget = { fg = theme.syn.special3 },
        NeotestTest = { fg = theme.ui.float.fg },
        NeotestUnknown = { fg = theme.syn.deprecated },
        NeotestWatching = { fg = theme.vcs.changed },
        typescriptExport = { fg = theme.syn.opkeyword, italic = true },
        typescriptGlobal = { fg = theme.syn.preproc, italic = true },
        typescriptImport = { fg = theme.syn.statement },
        typescriptDefault = { fg = theme.syn.constant, italic = true },
        typescriptFuncName = { fg = theme.syn.type },
        typescriptConsoleMethod = { fg = theme.syn.parameter },
        typescriptCall = { fg = theme.ui.fg_bright },

        htmlTag = { fg = theme.syn.deprecated },
        tsxAttrib = { fg = theme.syn.type },

        -- Start vim plugins
        ALEErrorSign = { fg = '#d6a477', bg = '#3a3a3a' },
        ALEWarningSign = { fg = '#d6a477', bg = '#3a3a3a' },
        ALEInfoSign = { fg = '#31a6a5', bg = '#3a3a3a' },
        DirvishPathTail = { fg = '#00d4f8' },
        DirvishArg = { fg = '#d6a477' },
        netrwDir = { fg = '#00d4f8' },
        netrwClassify = { fg = '#00d4f8' },
        netrwLink = { fg = '#808080' },
        netrwSymLink = { fg = '#f7f0f6' },
        netrwExe = { fg = '#d6a477' },
        netrwComment = { fg = '#808080' },
        netrwList = { fg = '#31a6a5' },
        netrwHelpCmd = { fg = '#00d4f8' },
        netrwCmdSep = { fg = '#dadada' },
        netrwVersion = { fg = '#b581b0' },
        BufferTabpageFill = { fg = '#f8eff7' },
        BufferCurrent = { fg = '#f8eff7', bg = '#222222' },
        BufferCurrentIndex = { fg = '#dadada', bg = '#222222' },
        BufferCurrentMod = { fg = '#ffd5d6', bg = '#222222' },
        BufferCurrentSign = { fg = '#222222', bg = '#222222' },
        BufferCurrentTarget = { fg = '#222222', bg = '#222222' },
        BufferVisible = { fg = '#c2c2c2', bg = '#181818' },
        BufferVisibleIndex = { fg = '#dadada', bg = '#222222' },
        BufferVisibleMod = { fg = '#ffd5d6', bg = '#181818' },
        BufferVisibleSign = { fg = '#181818', bg = '#181818' },
        BufferVisibleTarget = { fg = '#222222', bg = '#222222' },
        BufferInactive = { fg = '#c2c2c2', bg = '#181818' },
        BufferInactiveIndex = { fg = '#dadada', bg = '#222222' },
        BufferInactiveMod = { fg = '#ffd5d6', bg = '#181818' },
        BufferInactiveSign = { fg = '#181818', bg = '#181818' },
        BufferInactiveTarget = { fg = '#222222', bg = '#222222' },
        BufferAlternate = { fg = '#c2c2c2', bg = '#181818' },
        BufferAlternateSign = { fg = '#181818', bg = '#181818' },
        BufferAlternateIndex = { fg = '#dadada', bg = '#222222' },
        BufferAlternateMod = { fg = '#ffd5d6', bg = '#181818' },
        BufferAlternateTarget = { fg = '#222222', bg = '#222222' },
        NERDTreeDir = { fg = '#00d4f8' },
        NERDTreeDirSlash = { fg = '#00d4f8' },
        NERDTreeOpenable = { fg = '#94ffff' },
        NERDTreeClosable = { fg = '#94ffff' },
        NERDTreeFile = { fg = '#f7f0f6' },
        NERDTreeExecFile = { fg = '#d6a477' },
        NERDTreeUp = { fg = '#808080' },
        NERDTreeCWD = { fg = '#b581b0' },
        NERDTreeHelp = { fg = '#f7f0f6' },
        NERDTreeToggleOn = { fg = '#b581b0' },
        NERDTreeToggleOff = { fg = '#d6a477' },
        NeoTreeDirectoryIcon = { fg = '#00d4f8' },
        NeoTreeDirectoryName = { fg = '#f7f0f6' },
        NeoTreeWinSeparator = { fg = '#222222' },
        NeoTreeGitAdded = { fg = '#00d4f8' },
        NeoTreeGitConflict = { fg = '#00d4f8' },
        NeoTreeGitDeleted = { fg = '#00d4f8' },
        NeoTreeGitIgnored = { fg = '#00d4f8' },
        NeoTreeGitModified = { fg = '#00d4f8' },
        NeoTreeGitStaged = { fg = '#00d4f8' },
        NeoTreeGitRenamed = { fg = '#00d4f8' },
        NeoTreeGitUntracked = { fg = '#00d4f8' },
        CocErrorSign = { fg = '#bb595c' },
        CocUnusedHighlight = { fg = '#31a6a5' },
        CocWarningSign = { fg = '#d6a477' },
        CocInfoSign = { fg = '#d0d0d0' },
        CocHintSign = { fg = '#b8cfe6' },
        CocErrorFloat = { fg = '#d6a477' },
        CocWarningFloat = { fg = '#f8eff7' },
        CocInfoFloat = { fg = '#d6a477' },
        CocHintFloat = { fg = '#31a6a5' },
        CocDiagnosticsError = { fg = '#bb595c' },
        CocDiagnosticsWarning = { fg = '#d6a477' },
        CocDiagnosticsInfo = { fg = '#f8eff7' },
        CocDiagnosticsHint = { fg = '#31a6a5' },
        CocFloatBorderHighlight = { fg = '#d6a477' },
        CocSelectedText = { fg = '#ffd5d6' },
        CocCodeLens = { fg = '#b581b0' },
        CocFloatingBackground = { fg = '#f7f0f6' },
        CocFloatActive = { fg = '#b581b0' },
        CocSearch = { fg = '#e7477e' },
        CocPumMenu = { fg = '#ffd5d6' },
        CocMenuSel = { fg = '#0089ff', bg = '#f8eff7' },
        NormalFloat = { fg = '#f8eff7', bg = '#212121' },
        FloatBorder = { fg = '#757575' },
        DiagnosticError = { fg = '#ff0000' },
        diffAdded = { fg = '#b581b0' },
        diffRemoved = { fg = '#d6a477' },
        diffChanged = { fg = '#00d4f8' },
        diffFile = { fg = '#94ffff' },
        diffNewFile = { fg = '#d6a477' },
        diffLine = { fg = '#31a6a5' },
        htmlEndTag = { fg = '#31a6a5' },
        htmlTagName = { fg = '#d6a477' },
        htmlArg = { fg = '#2cf392' },
        htmlScriptTag = { fg = '#b581b0' },
        htmlTagN = { fg = '#f7f0f6' },
        htmlSpecialTagName = { fg = '#d6a477' },
        htmlSpecialChar = { fg = '#94ffff' },
        xmlTag = { fg = '#31a6a5' },
        xmlEndTag = { fg = '#31a6a5' },
        xmlTagName = { fg = '#31a6a5' },
        xmlEqual = { fg = '#31a6a5' },
        docbkKeyword = { fg = '#00d4f8' },
        xmlDocTypeDecl = { fg = '#808080' },
        xmlDocTypeKeyword = { fg = '#b581b0' },
        xmlCdataStart = { fg = '#808080' },
        xmlCdataCdata = { fg = '#b581b0' },
        dtdFunction = { fg = '#808080' },
        dtdTagName = { fg = '#b581b0' },
        xmlAttrib = { fg = '#00d4f8' },
        xmlProcessingDelim = { fg = '#808080' },
        dtdParamEntityPunct = { fg = '#808080' },
        dtdParamEntityDPunct = { fg = '#808080' },
        xmlAttribPunct = { fg = '#808080' },
        xmlEntity = { fg = '#94ffff' },
        xmlEntityPunct = { fg = '#94ffff' },
        vimLet = { fg = '#2cf392' },
        vimNotation = { fg = '#94ffff' },
        vimNumber = { fg = '#dadada' },
        vimMapModKey = { fg = '#94ffff' },
        vimFuncSID = { fg = '#00d4f8' },
        vimSetSep = { fg = '#dadada' },
        vimSep = { fg = '#dadada' },
        vimContinue = { fg = '#dadada' },
        vimTodo = { fg = '#bb595c' },
        vimType = { fg = '#2cf392' },
        vimFuncName = { fg = '#bb595c' },
        vimCommand = { fg = '#d6a477' },
        vimFunc = { fg = '#94ffff' },
        vimVar = { fg = '#31a6a5' },
        vimFuncVar = { fg = '#dadada' },
        vimString = { fg = '#b581b0' },
        vimFunction = { fg = '#dadada' },
        vimBracket = { fg = '#f8eff7' },
        clojureKeyword = { fg = '#31a6a5' },
        clojureCond = { fg = '#94ffff' },
        clojureSpecial = { fg = '#94ffff' },
        clojureDefine = { fg = '#94ffff' },
        clojureFunc = { fg = '#d6a477' },
        clojureRepeat = { fg = '#d6a477' },
        clojureCharacter = { fg = '#00d4f8' },
        clojureStringEscape = { fg = '#00d4f8' },
        clojureException = { fg = '#d6a477' },
        clojureRegexp = { fg = '#00d4f8' },
        clojureRegexpEscape = { fg = '#00d4f8' },
        clojureRegexpMod = { fg = '#dadada' },
        clojureRegexpQuantifier = { fg = '#dadada' },
        clojureParen = { fg = '#dadada' },
        clojureAnonArg = { fg = '#d6a477' },
        clojureVariable = { fg = '#31a6a5' },
        clojureMacro = { fg = '#94ffff' },
        clojureMeta = { fg = '#d6a477' },
        clojureDeref = { fg = '#d6a477' },
        clojureQuote = { fg = '#d6a477' },
        clojureUnquote = { fg = '#d6a477' },
        cOperator = { fg = '#b581b0' },
        cStructure = { fg = '#94ffff' },
        pythonBuiltin = { fg = '#2cf392' },
        pythonStatement = { fg = '#d6a477' },
        pythonBuiltinObj = { fg = '#94ffff' },
        pythonBuiltinFunc = { fg = '#94ffff' },
        pythonFunction = { fg = '#00d4f8' },
        pythonDecorator = { fg = '#94ffff' },
        pythonDecoratorName = { fg = '#94ffff' },
        pythonInclude = { fg = '#31a6a5' },
        pythonImport = { fg = '#31a6a5' },
        pythonRun = { fg = '#31a6a5' },
        pythonCoding = { fg = '#31a6a5' },
        pythonOperator = { fg = '#d6a477' },
        pythonException = { fg = '#d6a477' },
        pythonExceptions = { fg = '#b581b0' },
        pythonBoolean = { fg = '#b581b0' },
        pythonDot = { fg = '#dadada' },
        pythonConditional = { fg = '#d6a477' },
        pythonRepeat = { fg = '#d6a477' },
        pythonDottedName = { fg = '#b581b0' },
        javaScriptBraces = { fg = '#f7f0f6' },
        javaScriptMember = { fg = '#00d4f8' },
        javaScriptNumber = { fg = '#b581b0' },
        javaScriptString = { fg = '#b581b0' },
        javaScriptNull = { fg = '#b581b0' },
        javaScriptParens = { fg = '#dadada' },
        javaScriptReserved = { fg = '#d6a477' },
        javaScriptFunction = { fg = '#31a6a5' },
        javaScriptIdentifier = { fg = '#31a6a5' },
        javaScriptGlobal = { fg = '#00d4f8' },
        javaScriptStatement = { fg = '#d6a477' },
        javaScriptType = { fg = '#2cf392' },
        javascriptFuncName = { fg = '#2cf392' },
        javascriptFuncArg = { fg = '#ccffff' },
        javascriptClassExtends = { fg = '#00d4f8' },
        javascriptDefault = { fg = '#d6a477' },
        javascriptClassName = { fg = '#d6a477' },
        javascriptClassSuperName = { fg = '#d6a477' },
        javascriptGlobal = { fg = '#d6a477' },
        javascriptEndColons = { fg = '#f7f0f6' },
        javascriptGlobalMethod = { fg = '#f7f0f6' },
        javascriptNodeGlobal = { fg = '#f7f0f6' },
        javascriptBOMWindowProp = {  },
        javascriptArrayMethod = { fg = '#f7f0f6' },
        javascriptArrayStaticMethod = { fg = '#f7f0f6' },
        javascriptCacheMethod = { fg = '#f7f0f6' },
        javascriptDateMethod = { fg = '#f7f0f6' },
        javascriptMathStaticMethod = { fg = '#f7f0f6' },
        javascriptURLUtilsProp = { fg = '#f7f0f6' },
        javascriptDOMDocMethod = { fg = '#f7f0f6' },
        javascriptDOMDocProp = { fg = '#f7f0f6' },
        javascriptBOMLocationMethod = { fg = '#f7f0f6' },
        javascriptBOMWindowMethod = { fg = '#f7f0f6' },
        javascriptStringMethod = { fg = '#f7f0f6' },
        javascriptVariable = { fg = '#d6a477' },
        javascripttdentifier = { fg = '#31a6a5' },
        javascriptIdentifierName = { fg = '#ffd5d6' },
        javascriptClassSuper = { fg = '#94ffff' },
        javascriptString = { fg = '#b581b0' },
        javascriptFuncKeyword = { fg = '#31a6a5' },
        javascriptAsyncFunc = { fg = '#00d4f8' },
        javascriptClassStatic = { fg = '#94ffff' },
        javascriptOperator = { fg = '#e7477e' },
        javascriptForOperator = { fg = '#d6a477' },
        javascriptYield = { fg = '#d6a477' },
        javascriptExceptions = { fg = '#d6a477' },
        javascriptMessage = { fg = '#d6a477' },
        javascriptTemplateSB = { fg = '#00d4f8' },
        javascriptTemplateSubstitution = { fg = '#f7f0f6' },
        javascriptLabel = { fg = '#31a6a5' },
        javascriptObjectLabel = { fg = '#f8eff7' },
        javascriptLogicSymbols = { fg = '#f7f0f6' },
        javascriptArrowFunc = { fg = '#ffd5d6' },
        javascriptDocParamName = { fg = '#d0d0d0' },
        javascriptDocTags = { fg = '#d0d0d0' },
        javascriptDocNotation = { fg = '#d0d0d0' },
        javascriptDocParamType = { fg = '#d0d0d0' },
        javascriptDocNamedParamType = { fg = '#d0d0d0' },
        javascriptBrackets = { fg = '#f7f0f6' },
        javascriptDOMElemAttrs = { fg = '#f7f0f6' },
        javascriptDOMEventMethod = { fg = '#f7f0f6' },
        javascriptDOMNodeMethod = { fg = '#f7f0f6' },
        javascriptDOMStorageMethod = { fg = '#f7f0f6' },
        javascriptHeadersMethod = { fg = '#f7f0f6' },
        javascriptAsyncFuncKeyword = { fg = '#d6a477' },
        javascriptAwaitFuncKeyword = { fg = '#d6a477' },
        javascriptImport = { fg = '#d6a477' },
        javascriptExport = { fg = '#00d4f8' },
        javascriptPropertyName = { fg = '#d6a477' },
        javascriptProp = { fg = '#d6a477' },
        javascriptClassKeyword = { fg = '#2cf392' },
        javascriptObjectMethodName = { fg = '#ccffff' },
        javascriptObjectMethod = { fg = '#ccffff' },
        javascriptMethodAccessor = { fg = '#ccffff' },
        javascriptMethodName = { fg = '#ccffff' },
        javascriptMethod = { fg = '#ccffff' },
        javascriptFuncCall = { fg = '#ccffff' },
        jsImport = { fg = '#d6a477' },
        jsExport = { fg = '#e7477e', italic = true },
        jsFrom = { fg = '#00d4f8' },
        jsObjectProp = { fg = '#f7f0f6' },
        jsArrowFunction = { fg = '#ffd5d6' },
        jsExtendsKeyword = { fg = '#2cf392' },
        jsExportDefault = { fg = '#ccffff', italic = true },
        jsTemplateBraces = { fg = '#00d4f8' },
        jsFunction = { fg = '#31a6a5' },
        jsFuncParens = { fg = '#dadada' },
        jsParens = { fg = '#f7f0f6' },
        jsNull = { fg = '#b581b0' },
        jsUndefined = { fg = '#bb595c' },
        jsReturn = { fg = '#d6a477' },
        jsFuncName = { fg = '#2cf392' },
        jsClassKeyword = { fg = '#2cf392' },
        jsClassFuncName = { fg = '#2cf392' },
        jsLet = { fg = '#31a6a5' },
        jsStorageClass = { fg = '#d6a477' },
        jsObject = { fg = '#94ffff' },
        jsObjectFuncName = { fg = '#2cf392' },
        jsSpecial = { fg = '#2cf392' },
        jsThis = { fg = '#31a6a5' },
        jsGlobalNodeObjects = { fg = '#00d4f8' },
        jsOperatorKeyword = { fg = '#e7477e' },
        jsGlobalObjects = { fg = '#00d4f8', italic = true },
        jsFuncCall = { fg = '#ccffff' },
        jsFuncArgs = { fg = '#b2b2b2' },
        jsVariableDef = { fg = '#f7f0f6' },
        jsObjectKey = { fg = '#f8eff7' },
        jsFuncBlock = { fg = '#f7f0f6' },
        jsAsyncKeyword = { fg = '#31a6a5' },
        typeScriptReserved = { fg = '#00d4f8' },
        typeScriptLabel = { fg = '#00d4f8' },
        typeScriptFuncKeyword = { fg = '#31a6a5' },
        typeScriptIdentifier = { fg = '#94ffff' },
        typeScriptBraces = { fg = '#f7f0f6' },
        typeScriptEndColons = { fg = '#f7f0f6' },
        typeScriptDOMObjects = { fg = '#f7f0f6' },
        typeScriptAjaxMethods = { fg = '#f7f0f6' },
        typeScriptLogicSymbols = { fg = '#f7f0f6' },
        typeScriptDocSeeTag = { fg = '#808080', italic = true },
        typeScriptDocParam = { fg = '#808080', italic = true },
        typeScriptDocTags = { fg = '#eeeeee', italic = true },
        typeScriptGlobalObjects = { fg = '#f7f0f6' },
        typeScriptParens = { fg = '#dadada' },
        typeScriptOpSymbols = { fg = '#dadada' },
        typeScriptHtmlElemProperties = { fg = '#f7f0f6' },
        typeScriptNull = { fg = '#b581b0' },
        typeScriptInterpolationDelimiter = { fg = '#00d4f8' },
        purescriptModuleKeyword = { fg = '#00d4f8' },
        purescriptModuleName = { fg = '#f7f0f6' },
        purescriptWhere = { fg = '#00d4f8' },
        purescriptDelimiter = { fg = '#d0d0d0' },
        purescriptType = { fg = '#f7f0f6' },
        purescriptImportKeyword = { fg = '#bb595c' },
        purescriptHidingKeyword = { fg = '#00d4f8' },
        purescriptAsKeyword = { fg = '#00d4f8' },
        purescriptStructure = { fg = '#00d4f8' },
        purescriptOperator = { fg = '#31a6a5' },
        purescriptTypeVar = { fg = '#f7f0f6' },
        purescriptConstructor = { fg = '#f7f0f6' },
        purescriptFunction = { fg = '#f7f0f6' },
        purescriptConditional = { fg = '#94ffff' },
        purescriptBacktick = { fg = '#94ffff' },
        coffeeExtendedOp = { fg = '#dadada' },
        coffeeSpecialOp = { fg = '#dadada' },
        coffeeCurly = { fg = '#94ffff' },
        coffeeParen = { fg = '#dadada' },
        coffeeBracket = { fg = '#94ffff' },
        rubyStringDelimiter = { fg = '#b581b0' },
        rubyTestMacro = { fg = '#e7477e', italic = true },
        rubyAssertion = { fg = '#ccffff', italic = true },
        rubyFunction = { fg = '#31a6a5' },
        rubyInterpolationDelimiter = { fg = '#00d4f8' },
        rubyInstanceVariable = { fg = '#31a6a5' },
        rubyBlockParameterList = { fg = '#94ffff' },
        rubyClassBlock = { fg = '#e7477e' },
        objcTypeModifier = { fg = '#d6a477' },
        objcDirective = { fg = '#31a6a5' },
        goDirective = { fg = '#00d4f8' },
        goConstants = { fg = '#b581b0' },
        goDeclaration = { fg = '#d6a477' },
        goDeclType = { fg = '#31a6a5' },
        goBuiltins = { fg = '#94ffff' },
        luaIn = { fg = '#d6a477' },
        luaFunction = { fg = '#00d4f8' },
        luaTable = { fg = '#94ffff' },
        moonSpecialOp = { fg = '#dadada' },
        moonExtendedOp = { fg = '#dadada' },
        moonFunction = { fg = '#dadada' },
        moonObject = { fg = '#d6a477' },
        javaAnnotation = { fg = '#31a6a5' },
        javaDocTags = { fg = '#00d4f8' },
        javaCommentTitle = { fg = '#eeeeee', italic = true },
        javaParen = { fg = '#dadada' },
        javaParen1 = { fg = '#dadada' },
        javaParen2 = { fg = '#dadada' },
        javaParen3 = { fg = '#dadada' },
        javaParen4 = { fg = '#dadada' },
        javaParen5 = { fg = '#dadada' },
        javaOperator = { fg = '#94ffff' },
        javaVarArg = { fg = '#b581b0' },
        elixirDocString = { fg = '#808080', italic = true },
        elixirStringDelimiter = { fg = '#b581b0' },
        elixirInterpolationDelimiter = { fg = '#00d4f8' },
        elixirModuleDeclaration = { fg = '#d6a477' },
        scalaNameDefinition = { fg = '#f7f0f6' },
        scalaCaseFollowing = { fg = '#f7f0f6' },
        scalaCapitalWord = { fg = '#f7f0f6' },
        scalaTypeExtension = { fg = '#f7f0f6' },
        scalaKeyword = { fg = '#d6a477' },
        scalaKeywordModifier = { fg = '#d6a477' },
        scalaSpecial = { fg = '#00d4f8' },
        scalaOperator = { fg = '#f7f0f6' },
        scalaTypeDeclaration = { fg = '#d6a477' },
        scalaTypeTypePostDeclaration = { fg = '#d6a477' },
        scalaInstanceDeclaration = { fg = '#f7f0f6' },
        scalaInterpolation = { fg = '#00d4f8' },
        markdownH1 = { fg = '#b581b0' },
        markdownH2 = { fg = '#b581b0' },
        markdownH3 = { fg = '#d6a477' },
        markdownH4 = { fg = '#d6a477' },
        markdownH5 = { fg = '#d6a477' },
        markdownH6 = { fg = '#d6a477' },
        markdownCode = { fg = '#00d4f8' },
        markdownCodeBlock = { fg = '#00d4f8' },
        markdownCodeDelimiter = { fg = '#00d4f8' },
        markdownBlockquote = { fg = '#808080' },
        markdownListMarker = { fg = '#808080' },
        markdownOrderedListMarker = { fg = '#808080' },
        markdownRule = { fg = '#808080' },
        markdownHeadingRule = { fg = '#808080' },
        markdownUrlDelimiter = { fg = '#dadada' },
        markdownLinkDelimiter = { fg = '#dadada' },
        markdownLinkTextDelimiter = { fg = '#dadada' },
        markdownHeadingDelimiter = { fg = '#94ffff' },
        markdownUrl = { fg = '#b581b0' },
        markdownUrlTitleDelimiter = { fg = '#808080' },
        markdownUrlTitle = { fg = '#808080' },
        haskellType = { fg = '#f7f0f6' },
        haskellIdentifier = { fg = '#f7f0f6' },
        haskellSeparator = { fg = '#f7f0f6' },
        haskellDelimiter = { fg = '#d0d0d0' },
        haskellOperators = { fg = '#31a6a5' },
        haskellBacktick = { fg = '#94ffff' },
        haskellStatement = { fg = '#94ffff' },
        haskellConditional = { fg = '#94ffff' },
        haskellLet = { fg = '#00d4f8' },
        haskellDefault = { fg = '#00d4f8' },
        haskellWhere = { fg = '#00d4f8' },
        haskellBottom = { fg = '#00d4f8' },
        haskellBlockKeywords = { fg = '#00d4f8' },
        haskellImportKeywords = { fg = '#00d4f8' },
        haskellDeclKeyword = { fg = '#00d4f8' },
        haskellDeriving = { fg = '#00d4f8' },
        haskellAssocType = { fg = '#00d4f8' },
        haskellNumber = { fg = '#b581b0' },
        haskellPragma = { fg = '#b581b0' },
        haskellString = { fg = '#b581b0' },
        haskellChar = { fg = '#b581b0' },
        jsonKeyword = { fg = '#b581b0' },
        jsonQuote = { fg = '#b581b0' },
        jsonBraces = { fg = '#f7f0f6' },
        jsonString = { fg = '#f7f0f6' },
    }
end

return M
